### ISSUE TITLE
Example Program not working 

### ISSUE THREAD

**Issue by j-koreth** [mirkosertic/Bytecoder#510] opened 2021-02-03 23:13 UTC
I can't seem to get Bytecoder to work with any of the JavaFX programs I have. Running it on the HelloWorld program also gave me issues on two different machines or on different java version. I'm not sure if I'm missing something so this is what I did. 

I create a file called HelloWorld.java with 

`public class HelloWorld { 
   public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}`

I compile it with `javac HelloWorld.java`

I download the executable jar and run `java -jar bytecoder-cli-2021-01-26-executable.jar -classpath=. -mainclass=HelloWorld -builddirectory=. -backend=js -minify=false`

This throws 

`Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 10
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at de.mirkosertic.bytecoder.backend.js.JSMinifier.toClassNameInternal(JSMinifier.java:75)
	at de.mirkosertic.bytecoder.backend.js.JSMinifier.toClassName(JSMinifier.java:64)
	at de.mirkosertic.bytecoder.backend.js.JSSSACompilerBackend.lambda$generateCodeFor$10(JSSSACompilerBackend.java:995)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at de.mirkosertic.bytecoder.backend.js.JSSSACompilerBackend.generateCodeFor(JSSSACompilerBackend.java:990)
	at de.mirkosertic.bytecoder.backend.js.JSSSACompilerBackend.generateCodeFor(JSSSACompilerBackend.java:61)
	at de.mirkosertic.bytecoder.backend.CompileTarget.compile(CompileTarget.java:310)
	at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:132)
	... 8 more`

**Comment by mirkosertic** [comment] 2021-02-04 11:53
Thank you for using Bytecoder!

**Comment by blackjyn** [comment] 2021-02-09 18:06
@j-koreth it works

**Comment by j-koreth** [comment] 2021-02-09 23:45
I figured it works and it seems really promising but I'm a little unfamiliar with using javac. Would I need to have a specific folder structure for the example program with the package name? I apologize if this is covered somewhere in the documentation.

**Comment by cd155** [comment] 2021-04-09 17:23
Hi I tried the example online, but it is fail for some reasons
Java code:
package bytecodertest;

public class HelloWorld {

    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}

command line:
java -jar bytecoder-cli-2021-03-08-executable.jar -classpath=. -mainclass=bytecodertest.HelloWorld -builddirectory=. -backend=wasm -minify=false

error:
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.ClassNotFoundException: bytecodertest.HelloWorld
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:124)
	... 8 more

**Comment by TerryGuo** [comment] 2021-05-10 12:21
@cd155 I ran into same problem and fixed it by creating a folder named bytecodertest and then moving HelloWorld.class into it. Then everything works fine.

**Comment by cd155** [comment] 2021-05-12 16:19
@TerryGuo thanks, good to know. My previous project has done, so I don't have a chance to evaluate the wasm implementation that Bytecoder provides. But still, thanks for the share.

**Comment by liubiaoyong** [comment] 2021-05-17 14:33
the example can not work for me!
I've created a folder named bytecodertest, and add package bytecodertest,  but this command: 

```shell
java -jar bytecoder-cli-2021-03-08-executable.jar -classpath=. -mainclass=bytecodertest.HelloWorld -builddirectory=. -backend=wasm -minify=false
```

just only show Usage.

please see  the details in the newest issue.

**Comment by mirkosertic** [comment] 2021-05-21 12:07
Are there still open issues here? It seems to me the package declaration issue has been clarified, so I'd like to close this issue then.

**Closed** 2021-06-29 15:26 UTC
Labels: question

**Comment by varunManjula** [comment] 2022-05-30 17:27
> Are there still open issues here? It seems to me the package declaration issue has been clarified, so I'd like to close this issue then.

Hi @mirkosertic, thank u for the ByteCoder!

Actually facing one issue, 
I am executing the code 
`package bytecodertest;

public class HelloWorld {

    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
`
and trying to convert to JS as per this documentation [https://mirkosertic.github.io/Bytecoder/chapter-1/page-1-a/](url), 

I am using this jar executable **bytecoder-cli-2021-11-02-executable.jar ** getting this as output of the cmd **java -jar bytecoder-cli-2021-11-02-executable.jar -classpath=. -mainclass=bytecodertest.HelloWorld -builddirectory=. -backend=js -minify=false** 

![image](https://user-images.githubusercontent.com/102520225/171038348-1c8587ed-c315-4c8a-967b-1d5f678e9c06.png)

Could u plz help here, am I missing something here.

**Comment by Heath123** [comment] 2022-06-04 19:16
> I ran into same problem and fixed it by creating a folder named bytecodertest and then moving HelloWorld.class into it. Then everything works fine.

@mirkosertic The docs still don't show this step

**Comment by t-katsumura** [comment] 2022-09-14 11:53
Hi there.
I had the same problem and this ( `I've created a folder named bytecodertest, and add package bytecodertest, but this command:` ) was same for me.

But finally, I solved with this way.

This is the directry structure
```
<current directry>
├ bytecodertest
│ └ HelloWorld.java
└ bytecoder-cli-2021-11-02-executable.jar
```

and `HelloWorld.java` is
```java
package bytecodertest;
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
```

then, generate `bytecodertest/HelloWorld.class` with
```
javac bytecodertest/HelloWorld.java
```

After that, generate `bytecodertest/HelloWorld.jar`.
This step is not written in the docs
```
jar cvf bytecodertest/HelloWorld.jar bytecodertest/HelloWorld.class
```

Finally, run this to obtain `bytecoder.js` (or `bytecoder.wasm`)
```
java -jar bytecoder-cli-2021-11-02-executable.jar -classpath=bytecodertest/HelloWorld.jar -mainclass=bytecodertest.HelloWorld -builddirectory=. -backend=js -minify=false
```

My environment is

```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```
