### ISSUE TITLE
Wasm compilation fails for java 20 classes with `record`

### ISSUE THREAD

**Issue by sureshg** [mirkosertic/Bytecoder#857] opened 2023-03-31 06:44 UTC
## Env
```bash
$  java --version
openjdk 20 2023-03-21
OpenJDK Runtime Environment Zulu20.28+85-CA (build 20+36)
OpenJDK 64-Bit Server VM Zulu20.28+85-CA (build 20+36, mixed mode, sharing)

$ bytecoder-cli-2023-03-28-executable.jar 
```
## Input Program

```java
import java.util.List;
import java.util.Objects;

import static java.lang.System.out;

public class Main {

    public static void main(String[] args) {
        out.println("Hello JVM Wasm");
        var persons = List.of(new Person("Foo", 40), new Person("Bar", 30));
        persons.forEach(out::println);
    }
}

record Person(String name, int age) {
    Person {
        Objects.requireNonNull(name);
        if (age <= 0) {
            throw new IllegalArgumentException("Invalid age " + age);
        }
    }
}
```

## Command

```bash
$  java -jar bytecoder-cli-2023-03-28-executable.jar compile wasm -classpath=. -mainclass=Main -builddirectory=.
```

## Error

```bash
Mar 30, 2023 11:39:51 PM de.mirkosertic.bytecoder.core.Slf4JLogger info
INFO: Compiling main class Main to directory .
Current Analysis Stack is :
Parsing method body of LPerson;.toString
  Visiting #2 ALOAD Stack size is 0 Source line 15
  Local 0 of type LPerson;
  Visiting #3 INVOKEDYNAMIC Stack size is 1 Source line 15
  Local 0 of type LPerson;
  Stack 0 of type LPerson;
de.mirkosertic.bytecoder.core.ir.AnalysisException: java.lang.StringIndexOutOfBoundsException: Index 8 out of bounds for length 8
        at de.mirkosertic.bytecoder.core.ir.ResolvedMethod.parseBody(ResolvedMethod.java:50)
        at de.mirkosertic.bytecoder.core.ir.ResolvedClass.resolveMethodInternal(ResolvedClass.java:133)
        at de.mirkosertic.bytecoder.core.ir.ResolvedClass.finalizeLinkingHierarchy(ResolvedClass.java:188)
        at de.mirkosertic.bytecoder.core.parser.CompileUnit.finalizeLinkingHierarchy(CompileUnit.java:235)
        at de.mirkosertic.bytecoder.cli.CompileJSCommand.call(CompileJSCommand.java:90)
        at de.mirkosertic.bytecoder.cli.CompileJSCommand.call(CompileJSCommand.java:41)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at de.mirkosertic.bytecoder.cli.BytecoderCLI.main(BytecoderCLI.java:24)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.StringIndexOutOfBoundsException: Index 8 out of bounds for length 8
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
        at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.lang.String.checkIndex(String.java:4575)
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:46)
        at java.base/java.lang.String.charAt(String.java:1535)
        at org.objectweb.asm.Type.getReturnTypeOffset(Type.java:392)
        at org.objectweb.asm.Type.getReturnType(Type.java:369)
        at org.objectweb.asm.Type.getReturnType(Type.java:358)
        at de.mirkosertic.bytecoder.core.parser.GraphParser.resolveMethodType(GraphParser.java:2281)
        at de.mirkosertic.bytecoder.core.parser.GraphParser.parseInvokeDynamicInsnNode(GraphParser.java:2354)
        at de.mirkosertic.bytecoder.core.parser.GraphParser.parse(GraphParser.java:2552)
        at de.mirkosertic.bytecoder.core.parser.GraphParser.parse(GraphParser.java:404)
        at de.mirkosertic.bytecoder.core.parser.GraphParser.<init>(GraphParser.java:149)
        at de.mirkosertic.bytecoder.core.ir.ResolvedMethod.parseBody(ResolvedMethod.java:45)
        ... 20 more

```

**Comment by mirkosertic** [comment] 2023-03-31 15:11
Thank you for using Bytecoder and this detailed bug report!

I will try to fix this asap.

**Comment by mirkosertic** [comment] 2023-04-03 10:37
The issue is fixed and will become available with the next release.

Where were some missing features regarding InvokeDynamic and Java 18 Indy Record bytecode for toString(), equals() and hashCode(). I also faced another Bug regarding static methods in interfaces, which is also fixed by this commit.

Thank you for your contribution!

**Closed by mirkosertic** 2023-04-03 10:37 UTC
Labels: bug
