### ISSUE TITLE
Resource Bundle: Missing getBundle() methods

### ISSUE THREAD

**Issue by MeFisto94** [mirkosertic/Bytecoder#331] opened 2020-02-12 02:25 UTC
`Cannot find static method getBundle in java/util/ResourceBundle with signature java.util.ResourceBundle(java.lang.String,java.util.Locale,java.lang.ClassLoader)`

Is there a way for the user to define classlib methods so they are just picked up? And if so, would it be able to override the default TResourceBundle?

Another question:
The RuntimeException from `de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:121)` doesn't seem to mention the right class, as the class it points out doesn't use ResourceBundles at all.

Thanks in Advance :)

**Comment by mirkosertic** [comment] 2020-02-12 16:01
Can you please post the complete log file? There are often nested exceptions, and only the root cause reveals where the problem is.

**Comment by MeFisto94** [comment] 2020-02-12 20:44
Unfortunately that is only mildly helpful, as the nesting seems to be too deep for the regular exception formatter to print the stacktrace.

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test:bytecoder'.
[omitted gradle internal stacktraces]
Caused by: java.lang.RuntimeException: Error linking class com.jme3.math.Vector3f
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:121)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionGETSTATIC.performLinking(BytecodeInstructionGETSTATIC.java:39)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:380)
	at de.mirkosertic.bytecoder.backend.CompileTarget.compile(CompileTarget.java:115)
	at de.mirkosertic.bytecoder.backend.CompileTarget$compile.call(Unknown Source)
	at com.github.MeFisto94.Bytecoder.BytecoderTask.exec(BytecoderTask.groovy:56)
[gradle internal stacktrace again]
Caused by: java.lang.IllegalStateException: Cannot find static method getBundle in java/util/ResourceBundle with signature java.util.ResourceBundle(java.lang.String,java.util.Locale,java.lang.ClassLoader)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:35)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolvePrivateMethod(BytecodeLinkedClass.java:355)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:40)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolvePrivateMethod(BytecodeLinkedClass.java:355)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:40)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveConstructorInvocation(BytecodeLinkedClass.java:330)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESPECIAL.performLinking(BytecodeInstructionINVOKESPECIAL.java:36)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveVirtualMethod(BytecodeLinkedClass.java:299)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKEVIRTUAL.performLinking(BytecodeInstructionINVOKEVIRTUAL.java:54)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveVirtualMethod(BytecodeLinkedClass.java:299)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKEVIRTUAL.performLinking(BytecodeInstructionINVOKEVIRTUAL.java:54)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveVirtualMethod(BytecodeLinkedClass.java:299)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKEVIRTUAL.performLinking(BytecodeInstructionINVOKEVIRTUAL.java:54)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:380)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:34)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:380)
	at de.mirkosertic.bytecoder.core.BytecodeInstructionINVOKESTATIC.performLinking(BytecodeInstructionINVOKESTATIC.java:34)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveMethodSignatureAndBody(BytecodeLinkedClass.java:410)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveStaticMethod(BytecodeLinkedClass.java:380)
	at de.mirkosertic.bytecoder.core.BytecodeLinkedClass.resolveClassInitializer(BytecodeLinkedClass.java:153)
	at de.mirkosertic.bytecoder.core.BytecodeLinkerContext.resolveClass(BytecodeLinkerContext.java:114)
	... 98 more
```

**Comment by mirkosertic** [comment] 2020-03-11 21:06
Hmm, are you trying to compile some JMonkey Engine classes with Bytecoder? Do you have a sample project I can checkout? I'd really like to dive deeper into this problem...

**Comment by MeFisto94** [comment] 2020-03-24 00:21
Sorry for the late reply, I completely forgot about it.
Yes, I am trying to compile jme for the web platform, but in it's current form the code isn't touched so far, as it's already failing at the mathematical questions which are pretty standalone usually. 

This is my Gradle File:
```gradle
buildscript {
    repositories {
        maven { url "https://jitpack.io" }
        mavenCentral()
    }

    dependencies {
        classpath 'com.github.MeFisto94:bytecoder-gradle-plugin:53bf4387a1'
    }
}

if (!hasProperty('mainClass')) {
    ext.mainClass = 'com.github.MeFisto94.web.test.Main'
}

repositories {
    mavenCentral()
}

apply plugin: 'application'
apply plugin: 'com.github.MeFisto94.Bytecoder'

dependencies {
    compile 'org.jmonkeyengine:jme3-core:3.3.0-beta1'
    compile 'org.jmonkeyengine:jme3-teavm:3.3.0-beta1'
}


bytecoder {
    mainClassName = 'com.github.MeFisto94.web.test.Main'
}
```

Currently `jme3-teavm` is only local, I've setup a gradle composite build and it basically builds the engine locally and adds my small module, but as the name suggests, it stems from my previous attempts with TeaVM and basically provides Dummy Implementations of Audio, GL, etc for the engine to at least boot up.

So basically I locally have the engine which is being compiled, so I could patch stuff that is incompatble and the test project, containing this:
```java
package com.github.MeFisto94.web.test;

import com.jme3.math.Vector3f;
import com.jme3.system.AppSettings;
import com.jme3.system.JmeSystem;
import com.jme3.system.JmeTeaVMSystem;
import org.teavm.interop.Import;
import org.teavm.jso.JSBody;

class Main {

    @JSBody(params = { "message" }, script = "console.log(message)")
    @Import(name = "console_log")
    public static native void log(String message);

    public static void main(String... args) {
        Vector3f v = Vector3f.UNIT_X;
        v = v.add(0f, 2f, 0f);
        v.normalizeLocal();
        log(v.toString());

        //log(System.getProperty("os.name"));
        //log(System.getProperty("os.arch"));
        JmeSystem.setDelegate(new JmeTeaVMSystem());
        log(JmeSystem.getPlatform().toString());

        WebApplication app = new WebApplication();
        AppSettings settings = new AppSettings(true);
        settings.setFrameRate(1);
        app.setSettings(settings);
        app.start();
    }
}
```

Also still TeaVM there, but that's the code causing Vector to be included, just a small test that this works. (I expect the other code in it's current form to fail, obviously)

**Comment by mirkosertic** [comment] 2020-03-27 09:25
Ah I see.

The problem is lacking support of `java.util.logging.Logger`. I'll try toimplement this.

**Comment by mirkosertic** [comment] 2020-04-08 07:55
Initial support for java.logging module was merged to master.

**Closed by mirkosertic** 2020-04-08 07:55 UTC
Labels: enhancement

**Comment by MeFisto94** [comment] 2020-04-09 22:05
I still get: 
> Cannot find virtual method log in non-abstract class java/util/logging/Logger with signature VOID(java.util.logging.Level,java.lang.String,java.lang.Throwable)

Have you thought about allowing users to specify class lib extensions, so they don't have to be part of Bytecoder itself?

**Comment by mirkosertic** [comment] 2020-04-10 09:11
I've implemented very basic support for the `java.logging` module. The logging method signatures with Exceptions are currently not supported, as Bytecoder itself does not support proper exception handling, at least only the JS backend does support exception handling.

It is not easy to make the OpenJDK classes linkable with Bytecoder, as Bytecoder is not a complete JVM, and might never be. If you want to extend the current supported functionality, you have to take a look at the T* classes. For instance java.util.logging.Logger is shadowed by TLogger.java, which is located in the Bytecoder java.logging module. If you are missing something, you have to implement it there. The Bytecoder shadow types overwrite very specific parts of the JDK to make them linkable.

Feel free to experiment a bit. Also, please file another Issue if you've got problems and need support. I'am always glad to help.
