### ISSUE TITLE
Wasm file size issue

### ISSUE THREAD

**Issue by objectProgrammer** [mirkosertic/Bytecoder#257] opened 2019-10-27 19:13 UTC
Comparing a simple Hello world application:

2019-08-30 produces a ~490K .wasm binary file
a540964c96c648bb24409dd8a5545e4f08e9a2a9 produces a ~660K .wasm binary file (which doesn't even work `TypeError: bytecoder.filehandles[handle] is undefined`)

Shouldn't Bytecoder produce relatively same output? 660K for a Hello world is way too much.

I thought Bytecoder only includes used parts of the classlib? Or is it something else that's causing this huge change in size? I have no idea why fileinputstream, fileoutputstream and unixfilesystem all appeared in the wasmbindings even though a Hello world definitely doesn't need these.

**Comment by mirkosertic** [comment] 2019-10-28 11:16
It is indeed a little bit too big. However, the new file-io classes were introduced to be compatible with default JDK behavior.

Bytecoder does only include statically required classes, fields and methods by default. The tricky part are class initializers, which are evaluated automatically and fully once a class is part of the dependency tree. The `java.lang.System` class is in most cases part of the dependency tree, and it has a class initializer which creates the `System.in`, `System.out` etc instances, which will include the FileIO-Streams etc.

I guess the best way to reduce the class dependency tree is to separate declaration and initialization of static final class members, which would require an ehancement of the classlibs.

**Comment by objectProgrammer** [comment] 2019-10-28 17:27
Indeed, switching from System.out.println(...) to Console.console().log(...) does decrease the size to ~600K AND solves the `bytecoder.filehandles[handle] is undefined` error, but that leaves 110K of seemingly useless data (compared to 2019-08-30), do you know what the cause of that might be?

**Comment by mirkosertic** [comment] 2019-10-28 19:42
My educated guess is either character sets or locale data, maybe both. I am investigating...

**Comment by objectProgrammer** [comment] 2019-10-28 19:48
Thank you for your efforts :-)

**Comment by mirkosertic** [comment] 2019-10-30 22:07
I found something. Indeed Charactervsets are linked multiple times, their JDK original implementation and also the shadow type. This is a bug. 

There is also a set of Unicode Character Entity converters now included which were not part of the 2019-08-30 build, but are required for full unicode support.  This needs some space, but is needed by design. Maybe the amout of space can be reduced once Locale support is implemented completely.

**Comment by mirkosertic** [comment] 2019-11-02 19:29
I will merge a bug fix for this soon.
In the future Bytecoder will use dynamic linking and only include a default set of CharactetSets and Unicode conversion tables.
The default will only include Latin1 conversion tables and US-ASCII, UTF-8, UTF-16 and ISO-8859-1 as CharacterSets.
This reduces the Hello-World size including FileIO-API to ~352kb.

**Comment by mirkosertic** [comment] 2019-11-03 10:28
Merged to master.

**Closed by mirkosertic** 2019-11-03 10:28 UTC
Labels: bug

**Comment by objectProgrammer** [comment] 2019-11-03 18:42
Thank you for this amazing improvement! Indeed, I got ~352K too but the `TypeError: bytecoder.filehandles[handle] is undefined` is still present when using System.out.println(...) so I'm going to prefer Console.console().log(...) as it also results in a smaller file size (~308K).
